"""Compatibility façade for the needs domain service modules."""

from apps.needs.constants import (
    ACTIVE_NEED_STATUSES,
    CUSTOMER_DEMAND_NEED_NOTES,
    EDITABLE_NEED_STATUSES,
    EXTERNAL_DEMAND_ACTIVE_STATUSES,
    EXTERNAL_DEMAND_EDITABLE_STATUSES,
    EXTERNAL_DEMAND_NOTES_MAX_LENGTH,
    EXTERNAL_DEMAND_SEARCH_QUERY_MAX_LENGTH,
    NEED_NOTES_MAX_LENGTH,
    NEED_RESPONSE_NOTES_MAX_LENGTH,
    NEEDS_SEARCH_QUERY_MAX_LENGTH,
    PLANNED_NEED_ORDER_STATUSES,
    PUBLIC_OFFERED_ORDER_STATUSES,
)
from apps.needs.audit import (
    audit_quantity as _audit_quantity,
    external_demand_audit_values as _external_demand_audit_values,
    need_audit_values as _need_audit_values,
    need_marketplace_audit_values as _need_marketplace_audit_values,
)
from apps.needs.coverage import (
    calculate_need_coverage,
    recalculate_need_status,
    recalculate_needs_for_order,
    resolve_need_status as _resolve_need_status,
)
from apps.needs.exceptions import DuplicateActiveNeedError
from apps.needs.external_demands import (
    _customer_demand_need_external_id,
    _forecast_active_listings_quantity,
    _forecast_available_date,
    _forecast_available_quantity,
    _get_customer_demand_need_for_product,
    _lock_need_for_customer_demand_sync,
    _set_external_demands_generated_need,
    _stock_active_listings_quantity,
    _stock_available_quantity,
    _stock_pending_need_responses_quantity,
    _validate_external_customer_demand_payload,
    build_external_demand_plans,
    calculate_external_demand_plan,
    cancel_external_customer_demand,
    create_external_customer_demand,
    evaluate_external_demand_conflict_with_listings,
    get_external_customer_demand_for_producer,
    get_external_customer_demand_summary,
    list_external_customer_demands,
    mark_external_customer_demand_fulfilled,
    sync_external_customer_demand_state_for_product,
    sync_need_from_external_demands,
    sync_safety_stock_from_external_demands,
    update_external_customer_demand,
)
from apps.needs.lifecycle import (
    create_need,
    create_or_update_need,
    get_need_for_producer,
    ignore_need,
    publish_need_to_marketplace,
    update_need,
    withdraw_need_from_marketplace,
)
from apps.needs.marketplace_queries import (
    _add_offered_quantity,
    _build_need_row,
    get_critical_stock_product_ids,
    get_need_candidate_products,
    get_need_response_counts_for_owner,
    get_public_offered_quantities_by_need,
    list_marketplace_my_needs,
    list_marketplace_my_published_needs,
    list_marketplace_public_needs,
)
from apps.needs.responses import (
    _build_need_response,
    _derive_need_response_state,
    _get_accepted_need_response_listing_ids,
    _get_need_response_listing_for_update,
    _get_need_response_listing_queryset,
    _get_need_response_listings_for_owner,
    _get_need_response_order_state_listing_ids,
    _listing_source_label,
    _resolve_persisted_need_response_status,
    build_need_response_for_listing,
    get_active_need_response_for_responder,
    get_editable_need_response_for_responder,
    get_need_response_listing_for_viewer,
    get_need_response_order_snapshot,
    get_need_response_summaries_for_responder,
    list_need_responses_for_owner,
    list_need_responses_for_responder,
    reject_need_response,
    sync_need_response_status_for_listing,
    update_need_response,
)
from apps.needs.types import NeedResponse, NeedResponseSummary
from apps.needs.utils import (
    as_local_date as _as_local_date,
    clean_optional_text as _clean_optional_text,
    get_need_edit_help_text,
    get_need_minimum_edit_quantity,
    is_listing_effectively_expired,
    is_uuid_like as _is_uuid_like,
    normalize_external_demands_search_query,
    normalize_needed_by_date as _normalize_needed_by_date,
    normalize_needs_search_query,
    producer_marketplace_display_name as _producer_marketplace_display_name,
    quantize_need_quantity as _quantize_need_quantity,
)
